// Generated by https://quicktype.io

export interface Player {
    Results: ResultElement[];
    Links:   Links;
}

export interface Links {
    Self: Self;
}

export interface Self {
    AuthorityId:                              string;
    Path:                                     string;
    QueryString:                              string;
    RetryPolicyId:                            string;
    TopicName:                                string;
    AcknowledgementTypeId:                    number;
    AuthenticationLifetimeExtensionSupported: boolean;
}

export interface ResultElement {
    Id:         string;
    ResultCode: number;
    Result:     ResultResult;
}

export interface ResultResult {
    ArenaStats:  Arena;
    PlayerId:    PlayerID;
    SpartanRank: number;
    Xp:          number;
}

export interface Arena {
    ArenaPlaylistStats?:            ArenaPlaylistStats[];
    HighestCsrAttained?:            HighestCsrAttained;
    ArenaGameBaseVariantStats?:     Arena[];
    TopGameBaseVariants?:           TopGameBaseVariant[];
    HighestCsrPlaylistId?:          string;
    HighestCsrSeasonId?:            string;
    ArenaPlaylistStatsSeasonId?:    string;
    TotalKills:                     number;
    TotalHeadshots:                 number;
    TotalWeaponDamage:              number;
    TotalShotsFired:                number;
    TotalShotsLanded:               number;
    WeaponWithMostKills:            Weapon;
    TotalMeleeKills:                number;
    TotalMeleeDamage:               number;
    TotalAssassinations:            number;
    TotalGroundPoundKills:          number;
    TotalGroundPoundDamage:         number;
    TotalShoulderBashKills:         number;
    TotalShoulderBashDamage:        number;
    TotalGrenadeDamage:             number;
    TotalPowerWeaponKills:          number;
    TotalPowerWeaponDamage:         number;
    TotalPowerWeaponGrabs:          number;
    TotalPowerWeaponPossessionTime: string;
    TotalDeaths:                    number;
    TotalAssists:                   number;
    TotalGamesCompleted:            number;
    TotalGamesWon:                  number;
    TotalGamesLost:                 number;
    TotalGamesTied:                 number;
    TotalTimePlayed:                string;
    TotalGrenadeKills:              number;
    MedalAwards:                    MedalAward[];
    DestroyedEnemyVehicles:         DestroyedEnemyVehicle[];
    EnemyKills:                     any[];
    WeaponStats:                    Weapon[];
    Impulses:                       Impulse[];
    TotalSpartanKills:              number;
    FastestMatchWin:                null | string;
    FlexibleStats?:                 FlexibleStats;
    GameBaseVariantId?:             string;
    PlaylistId?:                    string;
    MeasurementMatchesLeft?:        number;
    HighestCsr?:                    HighestCsrAttained | null;
    Csr?:                           HighestCsrAttained | null;
    CsrPercentile?:                 number | null;
}

export interface HighestCsrAttained {
    Tier:              number;
    DesignationId:     number;
    Csr:               number;
    PercentToNextTier: number;
    Rank:              number | null;
}

export interface DestroyedEnemyVehicle {
    Enemy:      Enemy;
    TotalKills: number;
}

export interface Enemy {
    BaseId:      number;
    Attachments: number[];
}

export interface FlexibleStats {
    MedalStatCounts:   StatCount[];
    ImpulseStatCounts: StatCount[];
    MedalTimelapses:   any[];
    ImpulseTimelapses: ImpulseTimelapse[];
}

export interface StatCount {
    Id:    string;
    Count: number;
}

export interface ImpulseTimelapse {
    Id:        string;
    Timelapse: string;
}

export interface Impulse {
    Id:    number;
    Count: number;
}

export interface MedalAward {
    MedalId: number;
    Count:   number;
}

export interface TopGameBaseVariant {
    GameBaseVariantRank:      number;
    NumberOfMatchesCompleted: number;
    GameBaseVariantId:        string;
    NumberOfMatchesWon:       number;
}

export interface Weapon {
    WeaponId:            WeaponID;
    TotalShotsFired:     number;
    TotalShotsLanded:    number;
    TotalHeadshots:      number;
    TotalKills:          number;
    TotalDamageDealt:    number;
    TotalPossessionTime: string;
}

export interface WeaponID {
    StockId:     number;
    Attachments: any[];
}

export interface PlayerID {
    Gamertag: string;
    Xuid:     null;
}


// Generated by https://quicktype.io

export interface ArenaPlaylistStats {
    PlaylistId:                     string;
    MeasurementMatchesLeft:         number;
    HighestCsr:                     null;
    Csr:                            Csr;
    CsrPercentile:                  null;
    TotalKills:                     number;
    TotalHeadshots:                 number;
    TotalWeaponDamage:              number;
    TotalShotsFired:                number;
    TotalShotsLanded:               number;
    WeaponWithMostKills:            Weapon;
    TotalMeleeKills:                number;
    TotalMeleeDamage:               number;
    TotalAssassinations:            number;
    TotalGroundPoundKills:          number;
    TotalGroundPoundDamage:         number;
    TotalShoulderBashKills:         number;
    TotalShoulderBashDamage:        number;
    TotalGrenadeDamage:             number;
    TotalPowerWeaponKills:          number;
    TotalPowerWeaponDamage:         number;
    TotalPowerWeaponGrabs:          number;
    TotalPowerWeaponPossessionTime: string;
    TotalDeaths:                    number;
    TotalAssists:                   number;
    TotalGamesCompleted:            number;
    TotalGamesWon:                  number;
    TotalGamesLost:                 number;
    TotalGamesTied:                 number;
    TotalTimePlayed:                string;
    TotalGrenadeKills:              number;
    MedalAwards:                    MedalAward[];
    DestroyedEnemyVehicles:         any[];
    EnemyKills:                     any[];
    WeaponStats:                    Weapon[];
    Impulses:                       Impulse[];
    TotalSpartanKills:              number;
    FastestMatchWin:                string;
}
// Generated by https://quicktype.io

export interface Csr {
    Tier:              number;
    DesignationId:     number;
    Csr:               number;
    PercentToNextTier: number;
    Rank:              null;
}
